version: "3.9"
services:
  app:
    container_name: PriceServiceApplication
    command: java -jar target/PriceServiceApplication-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8083:8083
    expose:
      - 8083
    volumes:
      - ./:/app/app
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    name: KBE
    external: true


