version: "3.9"
services:
  app:
    container_name: PriceServiceApplication
    command: java -jar target/PriceServiceApplication-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8081:8081
    expose:
      - 8081
    volumes:
      - ./:/app/app



